USE [master]
GO
/****** Object:  Database [Asm_C2]    Script Date: 20/12/2019 2:13:34 PM ******/
CREATE DATABASE [Asm_C2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Asm_C2', FILENAME = N'D:\Poly\C2\Asm_C2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Asm_C2_log', FILENAME = N'D:\Poly\C2\Asm_C2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Asm_C2] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Asm_C2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Asm_C2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Asm_C2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Asm_C2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Asm_C2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Asm_C2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Asm_C2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Asm_C2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Asm_C2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Asm_C2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Asm_C2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Asm_C2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Asm_C2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Asm_C2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Asm_C2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Asm_C2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Asm_C2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Asm_C2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Asm_C2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Asm_C2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Asm_C2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Asm_C2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Asm_C2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Asm_C2] SET RECOVERY FULL 
GO
ALTER DATABASE [Asm_C2] SET  MULTI_USER 
GO
ALTER DATABASE [Asm_C2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Asm_C2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Asm_C2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Asm_C2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Asm_C2] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Asm_C2', N'ON'
GO
ALTER DATABASE [Asm_C2] SET QUERY_STORE = OFF
GO
USE [Asm_C2]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Asm_C2]
GO
/****** Object:  Table [dbo].[Class]    Script Date: 20/12/2019 2:13:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Class](
	[IdClass] [int] IDENTITY(1,1) NOT NULL,
	[NameClass] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Class] PRIMARY KEY CLUSTERED 
(
	[IdClass] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Student]    Script Date: 20/12/2019 2:13:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[StId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Mark] [float] NOT NULL,
	[Email] [varchar](100) NULL,
	[IdClass] [int] NOT NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[StId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Class] ON 

INSERT [dbo].[Class] ([IdClass], [NameClass]) VALUES (1, N'C1')
INSERT [dbo].[Class] ([IdClass], [NameClass]) VALUES (2, N'C2')
SET IDENTITY_INSERT [dbo].[Class] OFF
ALTER TABLE [dbo].[Student]  WITH CHECK ADD  CONSTRAINT [FK_Student_Class] FOREIGN KEY([IdClass])
REFERENCES [dbo].[Class] ([IdClass])
GO
ALTER TABLE [dbo].[Student] CHECK CONSTRAINT [FK_Student_Class]
GO
USE [master]
GO
ALTER DATABASE [Asm_C2] SET  READ_WRITE 
GO
